### ISSUE TITLE
single motor positioning 

### ISSUE THREAD

**Issue by radu022003** [Vinz1911/PrimePoweredUP#1]
hello,
i tried the example using one motor and using one of the commands: run_to_position, run_for_degrees, run_for_rotations and after first call the hub is freezing.
My guess is that these kind of functions are disturbing the Bluetooth communication.
MotorPair is just calling the motor.start() function 2 times. I have also tried the motor.start function and works without problem, because there is no loop that waits for finish and bluetooth communication is not disturbed.

**Comment by Vinx7a** [comment]
Do you have the "debugger" attached ? 

I discovered freezing problems if the hub ist connected to the PC via USB or Bluetooth Classic. I recommend just uploading it to the hub and then detach the hub from the pc and after that running it from the hub. 

i will later try the other commands you mentioned.

greetings
Vinz

**Comment by radu022003** [comment]
i have also tried without any connection to PC and the behavior was the same

**Comment by Vinx7a** [comment]
Alright, I could reproduced the error.

I'm not sure what happen here, maybe there is some strange behavior in the background between the ubluetooth class and the way how the other motor functions are implemented. For now I can't provide any solution :/. I hope LEGO is bringing back his own bluetooth class or support for bluetooth devices like the remote. With the latest Firmware the lego's own BLE class was removed. 

If I find any solution for this problem, I will update the code ASAP

**Comment by radu022003** [comment]
I will try some workaround, hopefully during weekend. 
Your examples are anyway really valuable and looks very nice.

**Comment by radu022003** [comment]
one of the approaches of mine regarding this topic was to use an event_loop:
from event_loop import get_event_loop
...
async def turn_right():
    steering_motor.run_for_degrees(-20)
...
if buttons[_BUTTON_A] == remote.BUTTON_A_PLUS and buttons[_BUTTON_B] == remote.BUTTON_B_RELEASED:
       loop.call_soon(turn_right())
....
loop = get_event_loop()

it runs good, sometimes there is a delay in these commands but is usable

**Comment by Vinx7a** [comment]
sounds great :) 

i will look into and maybe I can add some async functionality to the ble code and see if this will also resolve the freezing problem

**Comment by Vinx7a** [comment]
it tooked a while but with the current version of the library this problem should be resolved
